name: release
run-name: Release ${{ github.ref }} by ${{ github.actor }}
# Push events to matching v*, i.e. v1.0, v20.15.10, etc.
on:
  push:
    tags:
      - 'v*'
jobs:
  publish-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: "~> v1"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}