name: PR Test
on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]
    paths:
      - 'go.mod'
      - '**.go'
  workflow_dispatch: # for manual trigger
jobs:
  test:
    name: Test on go ${{ matrix.go }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ 1.22 ]
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go }}
        uses: WillAbides/setup-go-faster@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Unit Test
        run: go test ./... -covermode=atomic -vet=all -coverprofile=profile.cov